### ISSUE TITLE
Missing blur attribute

### ISSUE THREAD

**Issue by Bobtron** [larzm42/dom6inspector#9]
Gossamer Barding on the dom6 inspector is missing the blur attribute, which is present ingame. See images below

<img width="350" alt="Screen Shot 2024-03-10 at 13 28 57" src="https://github.com/larzm42/dom6inspector/assets/34115765/1f733fb9-6279-4e89-a091-61679af0172a">

<img width="500" alt="Screen Shot 2024-03-10 at 13 30 15" src="https://github.com/larzm42/dom6inspector/assets/34115765/77684856-3c36-4af8-bbf8-91d2fa47db55">

**Comment by larzm42** [comment]
blur is now added
